# This is a basic workflow that is manually triggered

name: Github Actions Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Downloading and setting up a requested version of Java
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    #  Configure Gradle for any platform supported by GitHub Actions.
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    # Execute default build to be sure project can be built
    - name: Execute Gradle build
      run: ./gradlew build -x allTests -x jvmTest

  detekt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Downloading and setting up a requested version of Java
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      #  Configure Gradle for any platform supported by GitHub Actions.
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # Execute default build to be sure project can be built
      - name: Execute Gradle detektAll
        run: ./gradlew detektAll